name: formobject
description: A dynamic objects to build UI widget input value with built-in validation and editor template
version: 1.0.0
homepage: https://github.com/hientrung/flutter-formobject

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  antlr4: 4.10.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
